apiVersion: v2
name: staysync
description: Stay Sync - Educational Assessment Platform
type: application
version: 1.0.0
appVersion: "1.0.0"
keywords:
  - education
  - assessment
  - flask
  - react
  - mongodb
home: https://pydahsoft.in
sources:
  - https://github.com/pydahsoft/staysync
maintainers:
  - name: PydahSoft Team
    email: support@pydahsoft.in
dependencies:
  - name: mongodb
    version: 13.6.0
    repository: https://charts.bitnami.com/bitnami
    condition: mongodb.enabled
  - name: redis
    version: 17.3.7
    repository: https://charts.bitnami.com/bitnami
    condition: redis.enabled
